# Code by 通义

# 定义工作流的名称
name: Build CSS

# 触发条件
on:
  # 在 main 分支上推送代码时触发
  push:
    branches:
      - main  # 或者你使用的其他分支
  # 在创建拉取请求时触发
  pull_request:

# 定义作业
jobs:
  # 定义一个名为 build 的作业
  build:
    # 运行环境
    runs-on: ubuntu-latest

    # 作业步骤
    steps:
    - name: Checkout repository  # 步骤名称
      uses: actions/checkout@v3  # 使用的 action

    - name: Set up Node.js  # 步骤名称
      uses: actions/setup-node@v3  # 使用的 action
      with:
        node-version: '18'  # 选择你想要的 Node.js 版本

    - name: Install dependencies  # 步骤名称
      run: npm install -g sass  # 执行的命令

    - name: Compile SCSS to CSS  # 步骤名称
      run: sass TideOS.scss:TideOS.css  # 执行的命令

    - name: Commit and push changes  # 步骤名称
      if: github.event_name == 'push'  # 只在推送事件时执行
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add TideOS.css
        git commit -m 'Build CSS' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 认证
